"""Entry point for ``python -m shantytown``.

Wires the persistent stores, the DMM API client, and the main window
together. Applies the saved theme before showing the window so we
don't flash with the default palette on first paint. On first run (no
profiles yet) we open the profile dialog proactively so the user has
somewhere to start.

CLI flags:

- ``--debug``: enables ``SHANTYTOWN_DEBUG`` / ``SHANTYTOWN_TELEMETRY``
  for verbose error reporting and (with an endpoint set) telemetry.
- ``--locale``: forces a specific UI language (``ko``/``en``).
- ``--show-tutorial``: re-runs the first-run walkthrough on this launch.
- ``--launch=<product_id>``: silent-launch shortcut entry point. If
  another instance is running, the request is forwarded over the
  single-instance pipe and this process exits. Otherwise we boot Qt
  but keep the main window hidden, run the launch flow, and quit
  cleanly on success — the desktop ``.lnk`` files generated by
  ``core.shortcuts`` use this flag.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import replace


def _parse_args(
    argv: list[str],
) -> tuple[bool, str | None, bool, str | None, bool, list[str]]:
    """Pull our flags out of ``argv`` so QApplication never sees them.

    Returns ``(debug, locale, show_tutorial, launch_id, show_webview,
    qt_argv)``. We use ``parse_known_args`` so Qt's own command-line
    flags (e.g. ``-platform offscreen`` for tests) pass through untouched.
    """
    parser = argparse.ArgumentParser(prog="shantytown", add_help=False)
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--locale", type=str, default=None)
    # Reveals the login webview (normally headless) so a developer can
    # watch the automated login and clear an interactive challenge by hand.
    parser.add_argument("--show-webview", action="store_true")
    # Forces the first-run tutorial to show on this launch regardless
    # of the saved ``tutorial_completed`` flag. Useful for re-watching
    # or for QA. The setting is *not* persisted — it's a per-run
    # override, not a reset.
    parser.add_argument("--show-tutorial", action="store_true")
    # Silent-launch flag set by desktop shortcuts. Empty string is
    # treated as absent (defensive — a malformed shortcut argument
    # shouldn't drop us into a launch flow with no product id).
    parser.add_argument("--launch", type=str, default=None)
    args, rest = parser.parse_known_args(argv[1:])
    launch_id: str | None = args.launch.strip() if args.launch else None
    if launch_id == "":
        launch_id = None
    return (
        args.debug,
        args.locale,
        args.show_tutorial,
        launch_id,
        args.show_webview,
        [argv[0], *rest],
    )


def _ensure_std_streams(debug: bool) -> None:
    """Make ``sys.stdout``/``sys.stderr`` safe to write to.

    A PyInstaller ``--windowed`` build has no console, so both streams are
    ``None`` and *any* write (``print(..., file=sys.stderr)``, a library
    logging to stderr, …) raises ``AttributeError`` and crashes startup.
    Point the missing streams at a target: a ``debug.log`` file under the
    app-data logs dir when ``--debug`` (so diagnostics survive), otherwise
    the null device. No-op in a normal console/dev run where the streams
    already exist.
    """
    if sys.stdout is not None and sys.stderr is not None:
        return
    sink = None
    if debug:
        try:
            from shantytown.store.paths import get_logs_dir

            # Kept open for the process lifetime (like the real streams).
            sink = open(
                get_logs_dir() / "debug.log",
                "a",
                encoding="utf-8",
                buffering=1,
            )
        except OSError:
            sink = None
    if sink is None:
        sink = open(os.devnull, "w", encoding="utf-8")
    if sys.stdout is None:
        sys.stdout = sink
    if sys.stderr is None:
        sys.stderr = sink


def main(argv: list[str] | None = None) -> int:
    """Boot the 판자촌 GUI."""
    raw_argv = list(argv if argv is not None else sys.argv)
    (
        debug,
        locale_override,
        force_tutorial,
        launch_id,
        show_webview,
        qt_argv,
    ) = _parse_args(raw_argv)

    # Do this first: in a windowed build the std streams are None and any
    # later write would crash before we ever reach the UI.
    _ensure_std_streams(debug)

    # Initialise i18n before any string-using code runs. This way both
    # the debug warning below and every QApplication child string sees
    # the active locale.
    from shantytown.core.i18n import init_translator

    init_translator(locale_override)

    if show_webview:
        os.environ["SHANTYTOWN_SHOW_WEBVIEW"] = "1"

    if debug:
        os.environ["SHANTYTOWN_DEBUG"] = "1"
        os.environ.setdefault("SHANTYTOWN_TELEMETRY", "1")
        if not os.environ.get("SHANTYTOWN_TELEMETRY_ENDPOINT"):
            sys.stderr.write(
                "[debug] Telemetry flag enabled but no endpoint set — "
                "set SHANTYTOWN_TELEMETRY_ENDPOINT to actually send data.\n"
            )

    from PyQt6.QtCore import Qt, QTimer
    from PyQt6.QtNetwork import QLocalServer, QLocalSocket
    from PyQt6.QtWidgets import QApplication

    from shantytown.core.api import DmmApiClient
    from shantytown.core.i18n import t
    from shantytown.gui.main_window import MainWindow
    from shantytown.gui.theme import apply_theme
    from shantytown.gui.tutorial_dialog import TutorialDialog
    from shantytown.store.games import GameStore
    from shantytown.store.paths import (
        get_games_path,
        get_profiles_path,
        get_settings_path,
    )
    from shantytown.store.profiles import ProfileStore
    from shantytown.store.settings import SettingsStore

    # QtWebEngine (used by the webview login agent) requires OpenGL context
    # sharing to be enabled before the QApplication is constructed. Setting
    # it unconditionally is cheap and harmless when WebEngine isn't used.
    QApplication.setAttribute(Qt.ApplicationAttribute.AA_ShareOpenGLContexts)

    app = QApplication(qt_argv)
    app.setApplicationName(t("app.name"))

    # --- single-instance enforcement ---
    #
    # ``QLocalServer`` is Qt's named-pipe wrapper (Windows: ``\\.\pipe\``,
    # POSIX: AF_UNIX socket). Pipes/sockets are scoped to the current
    # user's session, which gives us the right isolation for free —
    # different OS users get their own first instance.
    #
    # If we can connect, another instance owns the pipe. We send a tiny
    # "raise" message and exit; that instance's ``newConnection`` slot
    # brings its window to the foreground so the user sees they double-
    # launched. If we can't connect, we're the first one — bind the
    # pipe ourselves and wire the same handler.
    SINGLE_INSTANCE_KEY = "shantytown-single-instance-v1"
    probe = QLocalSocket()
    probe.connectToServer(SINGLE_INSTANCE_KEY)
    if probe.waitForConnected(500):
        # Existing instance owns the pipe — forward our intent and exit.
        # ``raise`` brings the window forward; ``launch:<id>`` additionally
        # triggers a launch on the receiving side. The trailing newline
        # is a frame delimiter so a future multi-line protocol stays
        # backward-compatible.
        if launch_id is not None:
            payload = f"launch:{launch_id}\n".encode("ascii")
        else:
            payload = b"raise\n"
        probe.write(payload)
        probe.flush()
        probe.waitForBytesWritten(500)
        probe.disconnectFromServer()
        return 0
    probe.abort()

    instance_server = QLocalServer()
    # Clean up any stale pipe entry left by a previous crash.
    QLocalServer.removeServer(SINGLE_INSTANCE_KEY)
    instance_server.listen(SINGLE_INSTANCE_KEY)

    # Pin the app icon for the taskbar / alt-tab. ``MainWindow`` also
    # sets it on the window itself so the title bar gets the bitmap.
    from shantytown.gui.icons import app_icon

    app.setWindowIcon(app_icon())

    # Flatten the default Fusion gradient on buttons/dropdowns so the
    # whole UI reads as Fluent-tone surfaces. Specific widgets can still
    # override (primary/danger buttons in dialogs, the painted cards).
    app.setStyleSheet(
        """
        QPushButton {
            background-color: palette(button);
            color: palette(button-text);
            border: 1px solid palette(mid);
            border-radius: 4px;
            padding: 6px 14px;
            min-height: 18px;
        }
        QPushButton:hover:!disabled {
            background-color: palette(midlight);
        }
        QPushButton:disabled {
            color: palette(placeholder-text);
        }
        QComboBox {
            background-color: palette(button);
            color: palette(button-text);
            border: 1px solid palette(mid);
            border-radius: 4px;
            padding: 4px 8px;
            min-height: 20px;
        }
        QComboBox::drop-down { border: none; width: 18px; }
        QComboBox QAbstractItemView {
            background-color: palette(base);
            color: palette(text);
            border: 1px solid palette(mid);
            selection-background-color: palette(highlight);
            selection-color: palette(highlighted-text);
            outline: 0;
        }
        QLineEdit {
            background-color: palette(base);
            color: palette(text);
            border: 1px solid palette(mid);
            border-radius: 4px;
            padding: 4px 8px;
        }
        QScrollArea { border: none; }
        """
    )

    settings_store = SettingsStore(get_settings_path())
    apply_theme(app, settings_store.get().theme)

    profile_store = ProfileStore(get_profiles_path())
    game_store = GameStore(get_games_path())
    api = DmmApiClient()

    window = MainWindow(
        api=api,
        profile_store=profile_store,
        game_store=game_store,
        settings_store=settings_store,
    )
    if launch_id is None:
        window.show()
    # Silent-launch path keeps the window hidden until something forces
    # it visible (missing config, expired token, error). The flow is
    # kicked off on the next event-loop tick so QApplication has fully
    # initialised before we start opening dialogs.

    def _on_second_instance() -> None:
        """A second launch pinged us — bring our window to the front,
        and if the message carries a ``launch:<id>`` directive, dispatch
        it through the same path as a card click."""
        sock = instance_server.nextPendingConnection()
        message = ""
        if sock is not None:
            # ``newConnection`` fires on accept; the bytes may not have
            # arrived yet, so wait briefly. Short messages always come
            # through in a single chunk on local sockets.
            if sock.waitForReadyRead(500):
                # ``QByteArray.data()`` returns ``bytes`` in PyQt6 — call
                # it explicitly so mypy doesn't complain about the
                # buffer-protocol path through ``bytes(...)``.
                message = (
                    sock.readAll().data().decode("ascii", errors="replace").strip()
                )
            sock.disconnectFromServer()
        if window.isMinimized():
            window.showNormal()
        else:
            window.show()
        window.raise_()
        window.activateWindow()
        if message.startswith("launch:"):
            forwarded_id = message[len("launch:") :].strip()
            if forwarded_id:
                window.handle_external_launch(forwarded_id)

    instance_server.newConnection.connect(_on_second_instance)

    # First-run walkthrough. Skipped entirely when ``--launch`` is set —
    # a desktop-shortcut click is a "play this game now" signal, not
    # a "give me an onboarding tour" signal. ``--show-tutorial`` is a
    # per-run override that does NOT update the saved flag.
    if launch_id is None:
        saved = settings_store.get()
        if force_tutorial or not saved.tutorial_completed:
            TutorialDialog(parent=window).exec()
            if not force_tutorial:
                # Preserve other settings fields (e.g. login_method) — only
                # tutorial_completed changes here.
                settings_store.update(replace(saved, tutorial_completed=True))

    if launch_id is not None:
        QTimer.singleShot(0, lambda: window.begin_silent_launch(launch_id))

    try:
        return app.exec()
    finally:
        api.close()


if __name__ == "__main__":
    raise SystemExit(main())
